void Ultrasonic_setup();
void Ultrasonic_loop();
extern int range;
// extern int cm;
extern int beep_counter;
extern int ultrasonic_measurment_timer;
extern bool ultrasonic_redy_for_servo;
extern int current_range_index;
// extern int buzzerPin;
// extern int buzzerPower;
// void Motor_setup();
// void Motor_loop();
